name: CI/CD - Build and Deploy on GitHub Runner

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: docker login -u "${{ secrets.DOCKHUB_UID }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Set Image Tag
        run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build --build-arg CACHEBUST=$(date +"%s") -t ${{ secrets.DOCKHUB_UID }}/inv-recon-agent:${{ env.IMAGE_TAG }} .

      - name: Push Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKHUB_UID }}/inv-recon-agent:${{ env.IMAGE_TAG }}

  deploy:
    name: Deploy on GitHub Runner
    needs: build-and-push  # Run only after build completes
    runs-on: ubuntu-latest

    steps:
      - name: Pull Image from Docker Hub
        run: docker pull ${{ secrets.DOCKHUB_UID }}/inv-recon-agent:latest

      - name: Stop and Remove Existing Container
        run: |
          docker stop inv-recon-agent || true
          docker rm inv-recon-agent || true

      - name: Run Container
        run: |
          docker run -d -p 5000:5000 --name inv-recon-agent \
            -e FLASK_DEBUG=True \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_REGION=us-east-1 \
            ${{ secrets.DOCKHUB_UID }}/inv-recon-agent:latest